# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AirQualityReading(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: datetime=None, pm2_5: float=None, pm10: float=None):  # noqa: E501
        """AirQualityReading - a model defined in Swagger

        :param timestamp: The timestamp of this AirQualityReading.  # noqa: E501
        :type timestamp: datetime
        :param pm2_5: The pm2_5 of this AirQualityReading.  # noqa: E501
        :type pm2_5: float
        :param pm10: The pm10 of this AirQualityReading.  # noqa: E501
        :type pm10: float
        """
        self.swagger_types = {
            'timestamp': datetime,
            'pm2_5': float,
            'pm10': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'pm2_5': 'pm2_5',
            'pm10': 'pm10'
        }
        self._timestamp = timestamp
        self._pm2_5 = pm2_5
        self._pm10 = pm10

    @classmethod
    def from_dict(cls, dikt) -> 'AirQualityReading':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AirQualityReading of this AirQualityReading.  # noqa: E501
        :rtype: AirQualityReading
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this AirQualityReading.

        Time of the air quality reading  # noqa: E501

        :return: The timestamp of this AirQualityReading.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this AirQualityReading.

        Time of the air quality reading  # noqa: E501

        :param timestamp: The timestamp of this AirQualityReading.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def pm2_5(self) -> float:
        """Gets the pm2_5 of this AirQualityReading.

        PM2.5 concentration in μg/m³  # noqa: E501

        :return: The pm2_5 of this AirQualityReading.
        :rtype: float
        """
        return self._pm2_5

    @pm2_5.setter
    def pm2_5(self, pm2_5: float):
        """Sets the pm2_5 of this AirQualityReading.

        PM2.5 concentration in μg/m³  # noqa: E501

        :param pm2_5: The pm2_5 of this AirQualityReading.
        :type pm2_5: float
        """

        self._pm2_5 = pm2_5

    @property
    def pm10(self) -> float:
        """Gets the pm10 of this AirQualityReading.

        PM10 concentration in μg/m³  # noqa: E501

        :return: The pm10 of this AirQualityReading.
        :rtype: float
        """
        return self._pm10

    @pm10.setter
    def pm10(self, pm10: float):
        """Sets the pm10 of this AirQualityReading.

        PM10 concentration in μg/m³  # noqa: E501

        :param pm10: The pm10 of this AirQualityReading.
        :type pm10: float
        """

        self._pm10 = pm10
