# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room_id: List[datetime]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param room_id: The room_id of this InlineResponse200.  # noqa: E501
        :type room_id: List[datetime]
        """
        self.swagger_types = {
            'room_id': List[datetime]
        }

        self.attribute_map = {
            'room_id': 'room_id'
        }
        self._room_id = room_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_id(self) -> List[datetime]:
        """Gets the room_id of this InlineResponse200.


        :return: The room_id of this InlineResponse200.
        :rtype: List[datetime]
        """
        return self._room_id

    @room_id.setter
    def room_id(self, room_id: List[datetime]):
        """Sets the room_id of this InlineResponse200.


        :param room_id: The room_id of this InlineResponse200.
        :type room_id: List[datetime]
        """

        self._room_id = room_id
