# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.light_reading import LightReading  # noqa: F401,E501
from swagger_server import util


class RoomLight(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, light: List[LightReading]=None):  # noqa: E501
        """RoomLight - a model defined in Swagger

        :param room: The room of this RoomLight.  # noqa: E501
        :type room: str
        :param light: The light of this RoomLight.  # noqa: E501
        :type light: List[LightReading]
        """
        self.swagger_types = {
            'room': str,
            'light': List[LightReading]
        }

        self.attribute_map = {
            'room': 'room',
            'light': 'light'
        }
        self._room = room
        self._light = light

    @classmethod
    def from_dict(cls, dikt) -> 'RoomLight':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomLight of this RoomLight.  # noqa: E501
        :rtype: RoomLight
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomLight.

        Room identifier  # noqa: E501

        :return: The room of this RoomLight.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomLight.

        Room identifier  # noqa: E501

        :param room: The room of this RoomLight.
        :type room: str
        """

        self._room = room

    @property
    def light(self) -> List[LightReading]:
        """Gets the light of this RoomLight.


        :return: The light of this RoomLight.
        :rtype: List[LightReading]
        """
        return self._light

    @light.setter
    def light(self, light: List[LightReading]):
        """Sets the light of this RoomLight.


        :param light: The light of this RoomLight.
        :type light: List[LightReading]
        """

        self._light = light
