# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.noise_reading import NoiseReading  # noqa: F401,E501
from swagger_server import util


class RoomNoise(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, airquality: List[NoiseReading]=None):  # noqa: E501
        """RoomNoise - a model defined in Swagger

        :param room: The room of this RoomNoise.  # noqa: E501
        :type room: str
        :param airquality: The airquality of this RoomNoise.  # noqa: E501
        :type airquality: List[NoiseReading]
        """
        self.swagger_types = {
            'room': str,
            'airquality': List[NoiseReading]
        }

        self.attribute_map = {
            'room': 'room',
            'airquality': 'airquality'
        }
        self._room = room
        self._airquality = airquality

    @classmethod
    def from_dict(cls, dikt) -> 'RoomNoise':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomNoise of this RoomNoise.  # noqa: E501
        :rtype: RoomNoise
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomNoise.

        Room identifier  # noqa: E501

        :return: The room of this RoomNoise.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomNoise.

        Room identifier  # noqa: E501

        :param room: The room of this RoomNoise.
        :type room: str
        """

        self._room = room

    @property
    def airquality(self) -> List[NoiseReading]:
        """Gets the airquality of this RoomNoise.


        :return: The airquality of this RoomNoise.
        :rtype: List[NoiseReading]
        """
        return self._airquality

    @airquality.setter
    def airquality(self, airquality: List[NoiseReading]):
        """Sets the airquality of this RoomNoise.


        :param airquality: The airquality of this RoomNoise.
        :type airquality: List[NoiseReading]
        """

        self._airquality = airquality
