# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.humidity_reading import HumidityReading  # noqa: F401,E501
from swagger_server import util


class RoomHumidity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, humidity: List[HumidityReading]=None):  # noqa: E501
        """RoomHumidity - a model defined in Swagger

        :param room: The room of this RoomHumidity.  # noqa: E501
        :type room: str
        :param humidity: The humidity of this RoomHumidity.  # noqa: E501
        :type humidity: List[HumidityReading]
        """
        self.swagger_types = {
            'room': str,
            'humidity': List[HumidityReading]
        }

        self.attribute_map = {
            'room': 'room',
            'humidity': 'humidity'
        }
        self._room = room
        self._humidity = humidity

    @classmethod
    def from_dict(cls, dikt) -> 'RoomHumidity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomHumidity of this RoomHumidity.  # noqa: E501
        :rtype: RoomHumidity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomHumidity.

        Room identifier  # noqa: E501

        :return: The room of this RoomHumidity.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomHumidity.

        Room identifier  # noqa: E501

        :param room: The room of this RoomHumidity.
        :type room: str
        """

        self._room = room

    @property
    def humidity(self) -> List[HumidityReading]:
        """Gets the humidity of this RoomHumidity.


        :return: The humidity of this RoomHumidity.
        :rtype: List[HumidityReading]
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: List[HumidityReading]):
        """Sets the humidity of this RoomHumidity.


        :param humidity: The humidity of this RoomHumidity.
        :type humidity: List[HumidityReading]
        """

        self._humidity = humidity
