# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.co2_reading import Co2Reading  # noqa: F401,E501
from swagger_server import util


class RoomCo2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, airquality: List[Co2Reading]=None):  # noqa: E501
        """RoomCo2 - a model defined in Swagger

        :param room: The room of this RoomCo2.  # noqa: E501
        :type room: str
        :param airquality: The airquality of this RoomCo2.  # noqa: E501
        :type airquality: List[Co2Reading]
        """
        self.swagger_types = {
            'room': str,
            'airquality': List[Co2Reading]
        }

        self.attribute_map = {
            'room': 'room',
            'airquality': 'airquality'
        }
        self._room = room
        self._airquality = airquality

    @classmethod
    def from_dict(cls, dikt) -> 'RoomCo2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomCo2 of this RoomCo2.  # noqa: E501
        :rtype: RoomCo2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomCo2.

        Room identifier  # noqa: E501

        :return: The room of this RoomCo2.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomCo2.

        Room identifier  # noqa: E501

        :param room: The room of this RoomCo2.
        :type room: str
        """

        self._room = room

    @property
    def airquality(self) -> List[Co2Reading]:
        """Gets the airquality of this RoomCo2.


        :return: The airquality of this RoomCo2.
        :rtype: List[Co2Reading]
        """
        return self._airquality

    @airquality.setter
    def airquality(self, airquality: List[Co2Reading]):
        """Sets the airquality of this RoomCo2.


        :param airquality: The airquality of this RoomCo2.
        :type airquality: List[Co2Reading]
        """

        self._airquality = airquality
