networks:
  default:
    driver: bridge
    ipam:
      driver: default
  nextcloud:
    driver: bridge
    internal: true
    ipam:
      driver: default

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    networks:
      - default
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/pwfile:/mosquitto/pwfile

  bridge:
    build: ./serial_mqtt_bridge
    container_name: bridge
    depends_on:
      - mosquitto
    devices:
      - "/dev:/dev"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    privileged: true
    links:
      - mosquitto
    tty: true

  simulator:
    build: ./simulator
    container_name: simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883

  dashboard:
    build: ./dashboard
    container_name: dashboard
    depends_on:
      - mosquitto
      - simulator
    ports:
      - "8501:8501"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - TOKEN=${TOKEN}
      - SERIAL_PORT=/dev/ttyACM0
      - MQTT_BROKER=${MQTT_BROKER}
    privileged: true
    links:
      - mosquitto

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: unless-stopped
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket

  mqtt_to_influx:
    build: ./mqtt_to_influx
    container_name: mqtt_to_influx
    depends_on:
      - influxdb
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - INFLUXDB_HOST=influxdb
    volumes:
      - ./mqtt_to_influx:/mqtt_to_influx
    command: python /mqtt_to_influx/mqtt_to_influx.py
    links:
      - influxdb
      - mosquitto
