networks:
  default:
    driver: bridge
    ipam:
      driver: default
  nextcloud:
    driver: bridge
    internal: true
    ipam:
      driver: default

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    networks:
      - default
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/pwfile:/mosquitto/pwfile

  bridge:
    build: ./serial_mqtt_bridge
    container_name: bridge
    depends_on:
      - mosquitto
    devices:
      - "/dev:/dev"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    privileged: true
    links:
      - mosquitto
    tty: true

  simulator:
    build: ./simulator
    container_name: simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883

  dashboard:
    build: ./dashboard
    container_name: dashboard
    depends_on:
      - mosquitto
      - simulator
    ports:
      - "8501:8501"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - TOKEN=${TOKEN}
