# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.equipments import Equipments  # noqa: F401,E501
from swagger_server import util


class RoomEquipment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, equipment: Equipments=None):  # noqa: E501
        """RoomEquipment - a model defined in Swagger

        :param room: The room of this RoomEquipment.  # noqa: E501
        :type room: str
        :param equipment: The equipment of this RoomEquipment.  # noqa: E501
        :type equipment: Equipments
        """
        self.swagger_types = {
            'room': str,
            'equipment': Equipments
        }

        self.attribute_map = {
            'room': 'room',
            'equipment': 'equipment'
        }
        self._room = room
        self._equipment = equipment

    @classmethod
    def from_dict(cls, dikt) -> 'RoomEquipment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomEquipment of this RoomEquipment.  # noqa: E501
        :rtype: RoomEquipment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomEquipment.

        Room identifier  # noqa: E501

        :return: The room of this RoomEquipment.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomEquipment.

        Room identifier  # noqa: E501

        :param room: The room of this RoomEquipment.
        :type room: str
        """

        self._room = room

    @property
    def equipment(self) -> Equipments:
        """Gets the equipment of this RoomEquipment.


        :return: The equipment of this RoomEquipment.
        :rtype: Equipments
        """
        return self._equipment

    @equipment.setter
    def equipment(self, equipment: Equipments):
        """Sets the equipment of this RoomEquipment.


        :param equipment: The equipment of this RoomEquipment.
        :type equipment: Equipments
        """

        self._equipment = equipment
