# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.temperature_reading import TemperatureReading  # noqa: F401,E501
from swagger_server import util


class RoomTemperature(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, temperature: List[TemperatureReading]=None):  # noqa: E501
        """RoomTemperature - a model defined in Swagger

        :param room: The room of this RoomTemperature.  # noqa: E501
        :type room: str
        :param temperature: The temperature of this RoomTemperature.  # noqa: E501
        :type temperature: List[TemperatureReading]
        """
        self.swagger_types = {
            'room': str,
            'temperature': List[TemperatureReading]
        }

        self.attribute_map = {
            'room': 'room',
            'temperature': 'temperature'
        }
        self._room = room
        self._temperature = temperature

    @classmethod
    def from_dict(cls, dikt) -> 'RoomTemperature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomTemperature of this RoomTemperature.  # noqa: E501
        :rtype: RoomTemperature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomTemperature.

        Room identifier  # noqa: E501

        :return: The room of this RoomTemperature.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomTemperature.

        Room identifier  # noqa: E501

        :param room: The room of this RoomTemperature.
        :type room: str
        """

        self._room = room

    @property
    def temperature(self) -> List[TemperatureReading]:
        """Gets the temperature of this RoomTemperature.


        :return: The temperature of this RoomTemperature.
        :rtype: List[TemperatureReading]
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: List[TemperatureReading]):
        """Sets the temperature of this RoomTemperature.


        :param temperature: The temperature of this RoomTemperature.
        :type temperature: List[TemperatureReading]
        """

        self._temperature = temperature
