# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.air_quality10_reading import AirQuality10Reading  # noqa: F401,E501
from swagger_server import util


class RoomAirQuality10(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, pm10: List[AirQuality10Reading]=None):  # noqa: E501
        """RoomAirQuality10 - a model defined in Swagger

        :param room: The room of this RoomAirQuality10.  # noqa: E501
        :type room: str
        :param pm10: The pm10 of this RoomAirQuality10.  # noqa: E501
        :type pm10: List[AirQuality10Reading]
        """
        self.swagger_types = {
            'room': str,
            'pm10': List[AirQuality10Reading]
        }

        self.attribute_map = {
            'room': 'room',
            'pm10': 'pm10'
        }
        self._room = room
        self._pm10 = pm10

    @classmethod
    def from_dict(cls, dikt) -> 'RoomAirQuality10':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomAirQuality10 of this RoomAirQuality10.  # noqa: E501
        :rtype: RoomAirQuality10
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomAirQuality10.

        Room identifier  # noqa: E501

        :return: The room of this RoomAirQuality10.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomAirQuality10.

        Room identifier  # noqa: E501

        :param room: The room of this RoomAirQuality10.
        :type room: str
        """

        self._room = room

    @property
    def pm10(self) -> List[AirQuality10Reading]:
        """Gets the pm10 of this RoomAirQuality10.


        :return: The pm10 of this RoomAirQuality10.
        :rtype: List[AirQuality10Reading]
        """
        return self._pm10

    @pm10.setter
    def pm10(self, pm10: List[AirQuality10Reading]):
        """Sets the pm10 of this RoomAirQuality10.


        :param pm10: The pm10 of this RoomAirQuality10.
        :type pm10: List[AirQuality10Reading]
        """

        self._pm10 = pm10
