# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.air_quality_reading import AirQualityReading  # noqa: F401,E501
from swagger_server import util


class RoomAirQuality(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, air_quality: List[AirQualityReading]=None):  # noqa: E501
        """RoomAirQuality - a model defined in Swagger

        :param room: The room of this RoomAirQuality.  # noqa: E501
        :type room: str
        :param air_quality: The air_quality of this RoomAirQuality.  # noqa: E501
        :type air_quality: List[AirQualityReading]
        """
        self.swagger_types = {
            'room': str,
            'air_quality': List[AirQualityReading]
        }

        self.attribute_map = {
            'room': 'room',
            'air_quality': 'air_quality'
        }
        self._room = room
        self._air_quality = air_quality

    @classmethod
    def from_dict(cls, dikt) -> 'RoomAirQuality':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomAirQuality of this RoomAirQuality.  # noqa: E501
        :rtype: RoomAirQuality
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomAirQuality.

        Room identifier  # noqa: E501

        :return: The room of this RoomAirQuality.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomAirQuality.

        Room identifier  # noqa: E501

        :param room: The room of this RoomAirQuality.
        :type room: str
        """

        self._room = room

    @property
    def air_quality(self) -> List[AirQualityReading]:
        """Gets the air_quality of this RoomAirQuality.


        :return: The air_quality of this RoomAirQuality.
        :rtype: List[AirQualityReading]
        """
        return self._air_quality

    @air_quality.setter
    def air_quality(self, air_quality: List[AirQualityReading]):
        """Sets the air_quality of this RoomAirQuality.


        :param air_quality: The air_quality of this RoomAirQuality.
        :type air_quality: List[AirQualityReading]
        """

        self._air_quality = air_quality
