# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.air_quality_reading import AirQualityReading  # noqa: F401,E501
from swagger_server.models.temperature_reading import TemperatureReading  # noqa: F401,E501
from swagger_server import util


class RoomData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: str=None, temperature: List[TemperatureReading]=None, air_quality: List[AirQualityReading]=None):  # noqa: E501
        """RoomData - a model defined in Swagger

        :param room: The room of this RoomData.  # noqa: E501
        :type room: str
        :param temperature: The temperature of this RoomData.  # noqa: E501
        :type temperature: List[TemperatureReading]
        :param air_quality: The air_quality of this RoomData.  # noqa: E501
        :type air_quality: List[AirQualityReading]
        """
        self.swagger_types = {
            'room': str,
            'temperature': List[TemperatureReading],
            'air_quality': List[AirQualityReading]
        }

        self.attribute_map = {
            'room': 'room',
            'temperature': 'temperature',
            'air_quality': 'air_quality'
        }
        self._room = room
        self._temperature = temperature
        self._air_quality = air_quality

    @classmethod
    def from_dict(cls, dikt) -> 'RoomData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomData of this RoomData.  # noqa: E501
        :rtype: RoomData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> str:
        """Gets the room of this RoomData.

        Room identifier  # noqa: E501

        :return: The room of this RoomData.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this RoomData.

        Room identifier  # noqa: E501

        :param room: The room of this RoomData.
        :type room: str
        """

        self._room = room

    @property
    def temperature(self) -> List[TemperatureReading]:
        """Gets the temperature of this RoomData.


        :return: The temperature of this RoomData.
        :rtype: List[TemperatureReading]
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: List[TemperatureReading]):
        """Sets the temperature of this RoomData.


        :param temperature: The temperature of this RoomData.
        :type temperature: List[TemperatureReading]
        """

        self._temperature = temperature

    @property
    def air_quality(self) -> List[AirQualityReading]:
        """Gets the air_quality of this RoomData.


        :return: The air_quality of this RoomData.
        :rtype: List[AirQualityReading]
        """
        return self._air_quality

    @air_quality.setter
    def air_quality(self, air_quality: List[AirQualityReading]):
        """Sets the air_quality of this RoomData.


        :param air_quality: The air_quality of this RoomData.
        :type air_quality: List[AirQualityReading]
        """

        self._air_quality = air_quality
