openapi: 3.0.0
info:
  title: Room Booking API
  description: API for ranking and booking rooms
  version: 1.0.0
servers:
- url: /
paths:
  /rank-rooms:
    get:
      tags:
      - Room Ranking
      summary: Get ranked list of available rooms
      operationId: rank_rooms
      parameters:
      - name: date
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2023-12-25
      - name: start_time
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: time
          example: 09:00:00
      - name: end_time
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: time
          example: 11:30:00
      - name: seating_capacity
        in: query
        required: true
        style: form
        explode: true
        schema:
          minimum: 1
          type: integer
          example: 10
      - name: projector
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: blackboard
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: smartboard
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: microphone
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: computer_class
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: pc
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: whiteboard
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: air_quality_preference
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: normal
          enum:
          - high
          - normal
      - name: noise_level
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: normal
          enum:
          - silent
          - normal
      - name: lighting
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: normal
          enum:
          - bright
          - normal
      responses:
        "200":
          description: Successfully returned ranked rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
                x-content-type: application/json
        "400":
          description: Invalid input parameters
      x-openapi-router-controller: swagger_server.controllers.room_ranking_controller
  /bookings:
    post:
      tags:
      - Booking
      summary: Book a specific room
      operationId: book_room
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookingRequest"
        required: true
      responses:
        "201":
          description: Room booked successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookingConfirmation"
        "400":
          description: Invalid booking request
        "404":
          description: Room not found
        "409":
          description: "Booking conflict, room unavailable"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookingRejection"
      security:
      - BearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.booking_controller
components:
  schemas:
    Room:
      type: object
      properties:
        room_id:
          type: string
          example: room-101
        rank:
          minimum: 1
          type: integer
          example: 1
        score:
          type: number
          format: float
          example: 8.7
        features:
          $ref: "#/components/schemas/Room_features"
      example:
        room_id: room-101
        score: 8.7
        blackboard: true
        co2: 0.8008281904610115
        pm10: 1.4658129805029452
        voc: 5.962133916683182
        computer_class: true
        whiteboard: true
        lighting: 2.3021358869347655
        pc: true
        seating_capacity: 30
        projector: true
        pm2_5: 6.027456183070403
        noise_level: 5.637376656633329
        humidity: 7.061401241503109
        microphone: true
        rank: 1
    BookingRequest:
      required:
      - date
      - end_time
      - room_id
      - start_time
      - user_name
      type: object
      properties:
        room_id:
          type: string
          example: room-101
        user_name:
          type: string
          example: abc123xyz
        date:
          type: string
          format: date
          example: 2023-12-25
        start_time:
          type: string
          format: time
          example: 09:00:00
        end_time:
          type: string
          format: time
          example: 11:30:00
    BookingConfirmation:
      type: object
      properties:
        booking_id:
          type: string
          example: booking-789
        status:
          type: string
          example: confirmed
        details:
          $ref: "#/components/schemas/Room"
      example:
        booking_id: booking-789
        room_id: room-101
        status: confirmed
    BookingRejection:
      type: object
      properties:
        booking_id:
          type: string
          example: booking-789
        room_id:
          type: string
          example: room-101
        status:
          type: string
          example: rejected
        rejection_reason:
          type: string
          example: Room not available
    Room_features:
      type: object
      properties:
        seating_capacity:
          type: integer
          example: 30
        projector:
          type: boolean
        computer_class:
          type: boolean
        blackboard:
          type: boolean
        microphone:
          type: boolean
        pc:
          type: boolean
        whiteboard:
          type: boolean
        co2:
          type: number
        pm2_5:
          type: number
        pm10:
          type: number
        voc:
          type: number
        noise_level:
          type: number
        lighting:
          type: number
        humidity:
          type: number
      example:
        blackboard: true
        co2: 0.8008281904610115
        pm10: 1.4658129805029452
        voc: 5.962133916683182
        computer_class: true
        whiteboard: true
        lighting: 2.3021358869347655
        pc: true
        seating_capacity: 30
        projector: true
        pm2_5: 6.027456183070403
        noise_level: 5.637376656633329
        humidity: 7.061401241503109
        microphone: true
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_BearerAuth

