# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.room import Room  # noqa: F401,E501
from swagger_server import util


class BookingConfirmation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, booking_id: str=None, status: str=None, details: Room=None):  # noqa: E501
        """BookingConfirmation - a model defined in Swagger

        :param booking_id: The booking_id of this BookingConfirmation.  # noqa: E501
        :type booking_id: str
        :param status: The status of this BookingConfirmation.  # noqa: E501
        :type status: str
        :param details: The details of this BookingConfirmation.  # noqa: E501
        :type details: Room
        """
        self.swagger_types = {
            'booking_id': str,
            'status': str,
            'details': Room
        }

        self.attribute_map = {
            'booking_id': 'booking_id',
            'status': 'status',
            'details': 'details'
        }
        self._booking_id = booking_id
        self._status = status
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'BookingConfirmation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookingConfirmation of this BookingConfirmation.  # noqa: E501
        :rtype: BookingConfirmation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def booking_id(self) -> str:
        """Gets the booking_id of this BookingConfirmation.


        :return: The booking_id of this BookingConfirmation.
        :rtype: str
        """
        return self._booking_id

    @booking_id.setter
    def booking_id(self, booking_id: str):
        """Sets the booking_id of this BookingConfirmation.


        :param booking_id: The booking_id of this BookingConfirmation.
        :type booking_id: str
        """

        self._booking_id = booking_id

    @property
    def status(self) -> str:
        """Gets the status of this BookingConfirmation.


        :return: The status of this BookingConfirmation.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this BookingConfirmation.


        :param status: The status of this BookingConfirmation.
        :type status: str
        """

        self._status = status

    @property
    def details(self) -> Room:
        """Gets the details of this BookingConfirmation.


        :return: The details of this BookingConfirmation.
        :rtype: Room
        """
        return self._details

    @details.setter
    def details(self, details: Room):
        """Sets the details of this BookingConfirmation.


        :param details: The details of this BookingConfirmation.
        :type details: Room
        """

        self._details = details
