# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RoomFeatures(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, seating_capacity: int=None, projector: bool=None, computer_class: bool=None, blackboard: bool=None, microphone: bool=None, pc: bool=None, whiteboard: bool=None, co2: float=None, pm2_5: float=None, pm10: float=None, voc: float=None, noise_level: float=None, lighting: float=None, humidity: float=None):  # noqa: E501
        """RoomFeatures - a model defined in Swagger

        :param seating_capacity: The seating_capacity of this RoomFeatures.  # noqa: E501
        :type seating_capacity: int
        :param projector: The projector of this RoomFeatures.  # noqa: E501
        :type projector: bool
        :param computer_class: The computer_class of this RoomFeatures.  # noqa: E501
        :type computer_class: bool
        :param blackboard: The blackboard of this RoomFeatures.  # noqa: E501
        :type blackboard: bool
        :param microphone: The microphone of this RoomFeatures.  # noqa: E501
        :type microphone: bool
        :param pc: The pc of this RoomFeatures.  # noqa: E501
        :type pc: bool
        :param whiteboard: The whiteboard of this RoomFeatures.  # noqa: E501
        :type whiteboard: bool
        :param co2: The co2 of this RoomFeatures.  # noqa: E501
        :type co2: float
        :param pm2_5: The pm2_5 of this RoomFeatures.  # noqa: E501
        :type pm2_5: float
        :param pm10: The pm10 of this RoomFeatures.  # noqa: E501
        :type pm10: float
        :param voc: The voc of this RoomFeatures.  # noqa: E501
        :type voc: float
        :param noise_level: The noise_level of this RoomFeatures.  # noqa: E501
        :type noise_level: float
        :param lighting: The lighting of this RoomFeatures.  # noqa: E501
        :type lighting: float
        :param humidity: The humidity of this RoomFeatures.  # noqa: E501
        :type humidity: float
        """
        self.swagger_types = {
            'seating_capacity': int,
            'projector': bool,
            'computer_class': bool,
            'blackboard': bool,
            'microphone': bool,
            'pc': bool,
            'whiteboard': bool,
            'co2': float,
            'pm2_5': float,
            'pm10': float,
            'voc': float,
            'noise_level': float,
            'lighting': float,
            'humidity': float
        }

        self.attribute_map = {
            'seating_capacity': 'seating_capacity',
            'projector': 'projector',
            'computer_class': 'computer_class',
            'blackboard': 'blackboard',
            'microphone': 'microphone',
            'pc': 'pc',
            'whiteboard': 'whiteboard',
            'co2': 'co2',
            'pm2_5': 'pm2_5',
            'pm10': 'pm10',
            'voc': 'voc',
            'noise_level': 'noise_level',
            'lighting': 'lighting',
            'humidity': 'humidity'
        }
        self._seating_capacity = seating_capacity
        self._projector = projector
        self._computer_class = computer_class
        self._blackboard = blackboard
        self._microphone = microphone
        self._pc = pc
        self._whiteboard = whiteboard
        self._co2 = co2
        self._pm2_5 = pm2_5
        self._pm10 = pm10
        self._voc = voc
        self._noise_level = noise_level
        self._lighting = lighting
        self._humidity = humidity

    @classmethod
    def from_dict(cls, dikt) -> 'RoomFeatures':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Room_features of this RoomFeatures.  # noqa: E501
        :rtype: RoomFeatures
        """
        return util.deserialize_model(dikt, cls)

    @property
    def seating_capacity(self) -> int:
        """Gets the seating_capacity of this RoomFeatures.


        :return: The seating_capacity of this RoomFeatures.
        :rtype: int
        """
        return self._seating_capacity

    @seating_capacity.setter
    def seating_capacity(self, seating_capacity: int):
        """Sets the seating_capacity of this RoomFeatures.


        :param seating_capacity: The seating_capacity of this RoomFeatures.
        :type seating_capacity: int
        """

        self._seating_capacity = seating_capacity

    @property
    def projector(self) -> bool:
        """Gets the projector of this RoomFeatures.


        :return: The projector of this RoomFeatures.
        :rtype: bool
        """
        return self._projector

    @projector.setter
    def projector(self, projector: bool):
        """Sets the projector of this RoomFeatures.


        :param projector: The projector of this RoomFeatures.
        :type projector: bool
        """

        self._projector = projector

    @property
    def computer_class(self) -> bool:
        """Gets the computer_class of this RoomFeatures.


        :return: The computer_class of this RoomFeatures.
        :rtype: bool
        """
        return self._computer_class

    @computer_class.setter
    def computer_class(self, computer_class: bool):
        """Sets the computer_class of this RoomFeatures.


        :param computer_class: The computer_class of this RoomFeatures.
        :type computer_class: bool
        """

        self._computer_class = computer_class

    @property
    def blackboard(self) -> bool:
        """Gets the blackboard of this RoomFeatures.


        :return: The blackboard of this RoomFeatures.
        :rtype: bool
        """
        return self._blackboard

    @blackboard.setter
    def blackboard(self, blackboard: bool):
        """Sets the blackboard of this RoomFeatures.


        :param blackboard: The blackboard of this RoomFeatures.
        :type blackboard: bool
        """

        self._blackboard = blackboard

    @property
    def microphone(self) -> bool:
        """Gets the microphone of this RoomFeatures.


        :return: The microphone of this RoomFeatures.
        :rtype: bool
        """
        return self._microphone

    @microphone.setter
    def microphone(self, microphone: bool):
        """Sets the microphone of this RoomFeatures.


        :param microphone: The microphone of this RoomFeatures.
        :type microphone: bool
        """

        self._microphone = microphone

    @property
    def pc(self) -> bool:
        """Gets the pc of this RoomFeatures.


        :return: The pc of this RoomFeatures.
        :rtype: bool
        """
        return self._pc

    @pc.setter
    def pc(self, pc: bool):
        """Sets the pc of this RoomFeatures.


        :param pc: The pc of this RoomFeatures.
        :type pc: bool
        """

        self._pc = pc

    @property
    def whiteboard(self) -> bool:
        """Gets the whiteboard of this RoomFeatures.


        :return: The whiteboard of this RoomFeatures.
        :rtype: bool
        """
        return self._whiteboard

    @whiteboard.setter
    def whiteboard(self, whiteboard: bool):
        """Sets the whiteboard of this RoomFeatures.


        :param whiteboard: The whiteboard of this RoomFeatures.
        :type whiteboard: bool
        """

        self._whiteboard = whiteboard

    @property
    def co2(self) -> float:
        """Gets the co2 of this RoomFeatures.


        :return: The co2 of this RoomFeatures.
        :rtype: float
        """
        return self._co2

    @co2.setter
    def co2(self, co2: float):
        """Sets the co2 of this RoomFeatures.


        :param co2: The co2 of this RoomFeatures.
        :type co2: float
        """

        self._co2 = co2

    @property
    def pm2_5(self) -> float:
        """Gets the pm2_5 of this RoomFeatures.


        :return: The pm2_5 of this RoomFeatures.
        :rtype: float
        """
        return self._pm2_5

    @pm2_5.setter
    def pm2_5(self, pm2_5: float):
        """Sets the pm2_5 of this RoomFeatures.


        :param pm2_5: The pm2_5 of this RoomFeatures.
        :type pm2_5: float
        """

        self._pm2_5 = pm2_5

    @property
    def pm10(self) -> float:
        """Gets the pm10 of this RoomFeatures.


        :return: The pm10 of this RoomFeatures.
        :rtype: float
        """
        return self._pm10

    @pm10.setter
    def pm10(self, pm10: float):
        """Sets the pm10 of this RoomFeatures.


        :param pm10: The pm10 of this RoomFeatures.
        :type pm10: float
        """

        self._pm10 = pm10

    @property
    def voc(self) -> float:
        """Gets the voc of this RoomFeatures.


        :return: The voc of this RoomFeatures.
        :rtype: float
        """
        return self._voc

    @voc.setter
    def voc(self, voc: float):
        """Sets the voc of this RoomFeatures.


        :param voc: The voc of this RoomFeatures.
        :type voc: float
        """

        self._voc = voc

    @property
    def noise_level(self) -> float:
        """Gets the noise_level of this RoomFeatures.


        :return: The noise_level of this RoomFeatures.
        :rtype: float
        """
        return self._noise_level

    @noise_level.setter
    def noise_level(self, noise_level: float):
        """Sets the noise_level of this RoomFeatures.


        :param noise_level: The noise_level of this RoomFeatures.
        :type noise_level: float
        """

        self._noise_level = noise_level

    @property
    def lighting(self) -> float:
        """Gets the lighting of this RoomFeatures.


        :return: The lighting of this RoomFeatures.
        :rtype: float
        """
        return self._lighting

    @lighting.setter
    def lighting(self, lighting: float):
        """Sets the lighting of this RoomFeatures.


        :param lighting: The lighting of this RoomFeatures.
        :type lighting: float
        """

        self._lighting = lighting

    @property
    def humidity(self) -> float:
        """Gets the humidity of this RoomFeatures.


        :return: The humidity of this RoomFeatures.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this RoomFeatures.


        :param humidity: The humidity of this RoomFeatures.
        :type humidity: float
        """

        self._humidity = humidity
