openapi: 3.0.0
info:
  title: Room Sensors API
  description: API for retrieving sensor data from different rooms
  version: 1.0.0
servers:
- url: http://localhost:8087
  description: Room Sensors
paths:
  /sensor/rooms:
    get:
      summary: Get sensor data for all rooms
      description: Retrieve all sensor data (temperature and air quality) for all
        rooms
      operationId: sensor_rooms_get
      responses:
        "200":
          description: A JSON array of rooms with their sensor data captured the past
            2 Weeks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomData'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /sensor/{room_id}:
    get:
      summary: Get sensor data for a specific room
      description: Retrieve all sensor data for a specific room
      operationId: sensor_room_id_get
      parameters:
      - name: room_id
        in: path
        description: Unique identifier for the room
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomData'
        "404":
          description: Room not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /rooms/airquality:
    get:
      summary: Get air quality data for all rooms
      description: Retrieve air quality measurements for all rooms
      operationId: rooms_airquality_get
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomAirQuality'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /rooms/temperature:
    get:
      summary: Get temperature data for all rooms
      description: Retrieve temperature measurements for all rooms
      operationId: rooms_temperature_get
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomTemperature'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /rooms/light:
    get:
      summary: Get light data for all rooms
      description: Retrieve light measurements for all rooms
      operationId: rooms_light_get
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomLight'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /rooms/humidity:
    get:
      summary: Get humidity data for all rooms
      description: Retrieve humidity measurements for all rooms
      operationId: rooms_humidity_get
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomHumidity'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /rooms/bookings:
    get:
      summary: Get bookings for all rooms
      description: Retrieve booking timestamps for all rooms within a specified time
        interval
      operationId: rooms_bookings_get
      parameters:
      - name: startDate
        in: query
        description: Start date for the booking period (YYYY-MM-DD)
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: days
        in: query
        description: Number of days to retrieve bookings for
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Successfully retrieved bookings for all rooms
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/Booking'
                example:
                  room001:
                  - 2024-12-01 17:30:00
                  - 2024-12-01 16:00:00
                  room002:
                  - 2024-12-02 17:30:00
                x-content-type: application/json
        "400":
          description: Invalid date format or days parameter
        "500":
          description: Internal server error
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /{room_id}/airquality:
    get:
      summary: Get air quality data for a specific room
      description: Retrieve air quality measurements for a specific room
      operationId: room_id_airquality_get
      parameters:
      - name: room_id
        in: path
        description: Unique identifier for the room
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomAirQuality'
        "404":
          description: Room not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /{room_id}/temperature:
    get:
      summary: Get temperature data for a specific room
      description: Retrieve temperature measurements for a specific room
      operationId: room_id_temperature_get
      parameters:
      - name: room_id
        in: path
        description: Unique identifier for the room
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomTemperature'
        "404":
          description: Room not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /{room_id}/humidity:
    get:
      summary: Get humidity data for a specific room
      description: Retrieve humidity measurements for a specific room
      operationId: room_id_humidity_get
      parameters:
      - name: room_id
        in: path
        description: Unique identifier for the room
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomHumidity'
        "404":
          description: Room not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /{room_id}/light:
    get:
      summary: Get light data for a specific room
      description: Retrieve light measurements for a specific room
      operationId: room_id_light_get
      parameters:
      - name: room_id
        in: path
        description: Unique identifier for the room
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomLight'
        "404":
          description: Room not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /{room_id}/bookings:
    get:
      summary: Get bookings for specific room
      description: Retrieve booking timestamps for a specific room within a specified
        time interval
      operationId: room_id_bookings_get
      parameters:
      - name: room_id
        in: path
        description: Unique identifier for the room
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: startDate
        in: query
        description: Start date for the booking period (YYYY-MM-DD)
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: days
        in: query
        description: Number of days to retrieve bookings for
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Successfully retrieved bookings for the specified room
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid date format or days parameter
        "404":
          description: Room not found
        "500":
          description: Internal server error
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    RoomData:
      type: object
      properties:
        room:
          type: string
          description: Room identifier
        temperature:
          type: array
          items:
            $ref: '#/components/schemas/TemperatureReading'
        air_quality:
          type: array
          items:
            $ref: '#/components/schemas/AirQualityReading'
        light:
          type: array
          items:
            $ref: '#/components/schemas/LightReading'
        humidity:
          type: array
          items:
            $ref: '#/components/schemas/HumidityReading'
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/Booking'
      example:
        light:
        - lumen: 1.4658129805029452
          timestamp: 2000-01-23T04:56:07.000+00:00
        - lumen: 1.4658129805029452
          timestamp: 2000-01-23T04:56:07.000+00:00
        temperature:
        - value: 0.8008282
          timestamp: 2000-01-23T04:56:07.000+00:00
        - value: 0.8008282
          timestamp: 2000-01-23T04:56:07.000+00:00
        humidity:
        - lumen: 5.962133916683182
          timestamp: 2000-01-23T04:56:07.000+00:00
        - lumen: 5.962133916683182
          timestamp: 2000-01-23T04:56:07.000+00:00
        air_quality:
        - co2: 6.027456183070403
          timestamp: 2000-01-23T04:56:07.000+00:00
        - co2: 6.027456183070403
          timestamp: 2000-01-23T04:56:07.000+00:00
        bookings:
        - 2000-01-23T04:56:07.000+00:00
        - 2000-01-23T04:56:07.000+00:00
        room: room
    RoomTemperature:
      type: object
      properties:
        room:
          type: string
          description: Room identifier
        temperature:
          type: array
          items:
            $ref: '#/components/schemas/TemperatureReading'
      example:
        temperature:
        - value: 0.8008282
          timestamp: 2000-01-23T04:56:07.000+00:00
        - value: 0.8008282
          timestamp: 2000-01-23T04:56:07.000+00:00
        room: room
    RoomAirQuality:
      type: object
      properties:
        room:
          type: string
          description: Room identifier
        air_quality:
          type: array
          items:
            $ref: '#/components/schemas/AirQualityReading'
      example:
        air_quality:
        - co2: 6.027456183070403
          timestamp: 2000-01-23T04:56:07.000+00:00
        - co2: 6.027456183070403
          timestamp: 2000-01-23T04:56:07.000+00:00
        room: room
    RoomLight:
      type: object
      properties:
        room:
          type: string
          description: Room identifier
        light:
          type: array
          items:
            $ref: '#/components/schemas/LightReading'
      example:
        light:
        - lumen: 1.4658129805029452
          timestamp: 2000-01-23T04:56:07.000+00:00
        - lumen: 1.4658129805029452
          timestamp: 2000-01-23T04:56:07.000+00:00
        room: room
    RoomHumidity:
      type: object
      properties:
        room:
          type: string
          description: Room identifier
        humidity:
          type: array
          items:
            $ref: '#/components/schemas/HumidityReading'
      example:
        humidity:
        - lumen: 5.962133916683182
          timestamp: 2000-01-23T04:56:07.000+00:00
        - lumen: 5.962133916683182
          timestamp: 2000-01-23T04:56:07.000+00:00
        room: room
    TemperatureReading:
      type: object
      properties:
        timestamp:
          type: string
          description: Time of the temperature reading
          format: date-time
        value:
          type: number
          description: Temperature value in Celsius
          format: float
      example:
        value: 0.8008282
        timestamp: 2000-01-23T04:56:07.000+00:00
    AirQualityReading:
      type: object
      properties:
        timestamp:
          type: string
          description: Time of the air quality reading
          format: date-time
        co2:
          type: number
          description: Concentration of CO2 in percentage %
      example:
        co2: 6.027456183070403
        timestamp: 2000-01-23T04:56:07.000+00:00
    LightReading:
      type: object
      properties:
        timestamp:
          type: string
          description: Time of the light reading
          format: date-time
        lumen:
          type: number
          description: Amount of light falling on a surface in lux = lumen/m2
      example:
        lumen: 1.4658129805029452
        timestamp: 2000-01-23T04:56:07.000+00:00
    HumidityReading:
      type: object
      properties:
        timestamp:
          type: string
          description: Time of the humidity reading
          format: date-time
        lumen:
          type: number
          description: amount of water vapor in the air relative to the maximum amount
            the air can hold at a given temperature in percent %
      example:
        lumen: 5.962133916683182
        timestamp: 2000-01-23T04:56:07.000+00:00
    Booking:
      type: string
      format: date-time
    inline_response_200:
      type: object
      properties:
        room_id:
          type: array
          items:
            $ref: '#/components/schemas/Booking'
      example:
        room001:
        - 2024-12-01 17:30:00
        - 2024-12-01 16:00:00

